### ISSUE TITLE
Using bugsy from the office fails (it might be slow internet)

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#102]
armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/generate_triggercli.py --back-revisions 2 --times 2 --bug-no 1011786
03/06/2015 02:00:04 INFO:	 Starting new HTTPS connection (1): bugzilla.mozilla.org
Traceback (most recent call last):
  File "scripts/generate_triggercli.py", line 168, in <module>
    main()
  File "scripts/generate_triggercli.py", line 61, in main
    search_dict = search_bug(bug_no)
  File "scripts/generate_triggercli.py", line 138, in search_bug
    bug = bugzilla.get(bug_no)
  File "build/bdist.linux-x86_64/egg/bugsy/bugsy.py", line 78, in get
  File "build/bdist.linux-x86_64/egg/bugsy/bugsy.py", line 128, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by vaibhavmagarwal** [comment]
Heh, we can't do anything about that in mozilla_ci_tools repo :)

**Comment by armenzg** [comment]
You're probably right :)
