### ISSUE TITLE
when we try to trigger on a DONTBUILD push, we error out of our scripts

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#113]
03/10/2015 01:44:06 INFO:	 === e750aa4fc06c ===
03/10/2015 01:44:06 INFO:	 We want to have 3 job(s) of Ubuntu HW 12.04 fx-team talos svgr on revision e750aa4fc06c
03/10/2015 01:44:06 INFO:	 We will _NOT_ trigger anything for revision e750aa4fc06c for fx-team since it does not exist in self-serve.
03/10/2015 01:44:06 ERROR:	 
Traceback (most recent call last):
  File "trigger_range.py", line 162, in <module>
    dry_run=options.dry_run
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 355, in trigger_range
    jobs = query_jobs(repo_name, rev)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 182, in query_jobs
    return buildapi.query_jobs_schedule(repo_name, revision)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildapi.py", line 150, in query_jobs_schedule
    raise BuildapiException
BuildapiException

here is the revision:
https://treeherder.mozilla.org/#/jobs?repo=fx-team&revision=e750aa4fc06c

I would expect that we would handle this better- maybe in trigger_range.

**Comment by armenzg** [comment]
Fixed:
https://github.com/armenzg/mozilla_ci_tools/commit/24cf894c8903df05bc0c81b2b81ecd6951fe950a
