### ISSUE TITLE
Recuperate better from a corrupted buildjson file on Windows

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#160]
avih hit this.

04/07/2015 11:04:52 ERROR:       The obtained json from http://builddata.pub.build.mozilla.org/builddata/buildjson/builds-4hr.js.gz came corrupted. We're not writing to disk."

2nd run:
$ python alltalos.py --repo-name try --rev 76b999af7321 --times 1
04/07/2015 11:12:47 INFO:        We want to trigger 'Android 4.0 armv7 API 11+ try talos remote-tp4m_nochrome' on revision '76b999af7321' a tot
al of 1 time(s).
Traceback (most recent call last):
  File "alltalos.py", line 81, in <module>
    main()
  File "alltalos.py", line 78, in main
    dry_run=options.dry_run)
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\mozci.py", line 335, in trigger_job
    buildername,
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\mozci.py", line 120, in _determine_trigger_objective
    status = buildapi.query_job_status(job)
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\sources\buildapi.py", line 143, in query_job_status
    req["request_id"])
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\sources\buildjson.py", line 155, in query_job_data
    job = _find_job(request_id, _fetch_file(BUILDS_4HR_FILE), BUILDS_4HR_FILE)
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\sources\buildjson.py", line 40, in _fetch_file
    fetch_file(filepath, url)
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\utils\transfer.py", line 80, in fetch_file
    _save_json_file(req, filename)
  File "e:\dev\moz\src\ci_tools-mozilla.github\mozci\utils\transfer.py", line 51, in _save_json_file
    shutil.move(temp_file.name, filename)
  File "d:\test-mozilla-build-2.0pre4\python\lib\shutil.py", line 303, in move
    os.unlink(src)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\duku\\appdata\\local\\temp\\tmpqcnlgb'

**Comment by armenzg** [comment]
We re-worked this piece of code a bit few weeks ago.
https://github.com/armenzg/mozilla_ci_tools/commit/e9ef90765ef6c9d444989bbdf545579970f1c138

From looking at the traceback, we should have not failed to move the temp file:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/utils/transfer.py#L77

We should probably add better file handling in there.

**Comment by vaibhavmagarwal** [comment]
This issue is the same as https://github.com/armenzg/mozilla_ci_tools/issues/197 and will be fixed in https://github.com/armenzg/mozilla_ci_tools/pull/205
