### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#187]
(venv)vaibhav@vaibhav:~/mozilla_ci_tools/scripts(master) $ python trigger.py --rev b4fd9967aa85 -b " Ubuntu HW 12.04 x64 fx-team talos g1 " --delta 2 --times 5 --dry-run
05/09/2015 12:45:24 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 x64 fx-team talos g1 on revisions [u'94ca3cad5caa', u'2357d7d9c25e', u'b4fd9967aa85', u'2e1d5dc5393f', u'a375bdb7fb5d']
05/09/2015 12:45:24 INFO:	 
05/09/2015 12:45:24 INFO:	 === 94ca3cad5caa ===
05/09/2015 12:45:24 ERROR:	 No JSON object could be decoded
Traceback (most recent call last):
  File "trigger.py", line 189, in <module>
    files=options.files
  File "build/bdist.linux-x86_64/egg/mozci/mozci.py", line 383, in trigger_range
    if not buildapi.valid_revision(repo_name, rev):
  File "build/bdist.linux-x86_64/egg/mozci/sources/buildapi.py", line 121, in valid_revision
    content = json.loads(req.content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This is the error I am getting on the latest commit of master.

**Comment by vaibhavmagarwal** [comment]
Looks like something was wrong in my virtualenv, did a fresh 'python setup.py develop' and now this is resolved.
