### ISSUE TITLE
MemoryError in Windows with gzip

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#202]
I get the following error on Windows:
(venv) C:\Users\Vaibhav\Desktop\mozilla_ci_tools\mozci\scripts>python trigger.py
 --rev b4fd9967aa85 -b "ubuntu hw 12.04 x64 fx-team talos g1" --delta 2 --times
5 --dry-run --debug

05/15/2015 02:52:45 DEBUG:       "GET /builddata/buildjson/builds-2015-04-30.js.
gz HTTP/1.1" 200 20720071
05/15/2015 02:52:45 DEBUG:       About to fetch C:\Users\Vaibhav/.mozilla/mozci/
builds-2015-04-30.js from http://builddata.pub.build.mozilla.org/builddata/build
json/builds-2015-04-30.js.gz
builds-2015-04-30.js: [>>>>>>>>>>>>>>] Elapsed Time: 0:00:17   1.21 MB/s 19.0MB
05/15/2015 02:53:02 DEBUG:       Let's decompress the received data.
05/15/2015 02:53:03 ERROR:
Traceback (most recent call last):
  File "trigger.py", line 189, in main
    files=options.files
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\mozci.py", line 394, in
trigger_range
    successful_jobs, pending_jobs, running_jobs = _status_summary(matching_jobs)
[0:3]
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\mozci.py", line 72, in _
status_summary
    status = buildapi.query_job_status(job)
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\sources\buildapi.py", li
ne 153, in query_job_status
    req["request_id"])
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\sources\buildjson.py", l
ine 158, in query_job_data
    jobs = _fetch_data(filename)
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\sources\buildjson.py", l
ine 42, in _fetch_data
    json_contents = load_file(filepath, url)
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\utils\transfer.py", line
 131, in load_file
    return _fetch_and_load_file(req, filepath)
  File "c:\users\vaibhav\desktop\mozilla_ci_tools\mozci\utils\transfer.py", line
 62, in _fetch_and_load_file
    blob = gzipper.read()
  File "C:\Python27(32bit)\Lib\gzip.py", line 249, in read
    self._read(readsize)
  File "C:\Python27(32bit)\Lib\gzip.py", line 308, in _read
    self._add_read_data( uncompress )
  File "C:\Python27(32bit)\Lib\gzip.py", line 326, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError

My machine has 6GB RAM, and this command runs properly on Ubuntu, so that is unlikely the cause. It has something to do with reading the whole file here: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/utils/transfer.py#L62

**Comment by armenzg** [comment]
Addressed in:
https://github.com/armenzg/mozilla_ci_tools/commit/e462ce5ac209f99f53f34c733d6a1806f468bdf9
