### ISSUE TITLE
Cannot find job ID for user cancelled job

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#216]
jmaher cannot find a specific ID in a builds-<date>.js file
it is probably because the build was user canceled.

https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=d0129aa5b896

jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/mozci/scripts$ python trigger.py -b 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' -r 6afb088b0cff --times 20 --back-revisions 30 --skips 5
05/19/2015 03:59:16 INFO:	 We want to have 20 job(s) of Windows 8 64-bit mozilla-inbound opt test mochitest-2 on revisions [u'6afb088b0cff', u'2321901d8d22', u'e6565b1773b8', u'0055add82982', u'd0129aa5b896', u'3026a0345003', u'b15dac9231ee']
05/19/2015 03:59:16 INFO:	 
05/19/2015 03:59:16 INFO:	 === 6afb088b0cff ===
05/19/2015 03:59:21 INFO:	 We want to have 20 job(s) of Windows 8 64-bit mozilla-inbound opt test mochitest-2 on revision 6afb088b0cff
05/19/2015 03:59:29 INFO:	 We have found 0 potential job(s) matching 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on 6afb088b0cff. We need to trigger more.
05/19/2015 03:59:29 INFO:	 We want to trigger 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on revision '6afb088b0cff' a total of 20 time(s).
builds-2015-05-12.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:23 807.29 kB/s 18.0MB
05/19/2015 04:00:21 INFO:	 There is a _build_ job that has completed successfully.
05/19/2015 04:00:21 INFO:	 We have the necessary files to trigger the downstream job.
05/19/2015 04:00:53 INFO:	 
05/19/2015 04:00:53 INFO:	 === 2321901d8d22 ===
05/19/2015 04:00:54 INFO:	 We want to have 20 job(s) of Windows 8 64-bit mozilla-inbound opt test mochitest-2 on revision 2321901d8d22
05/19/2015 04:00:55 INFO:	 We have found 0 potential job(s) matching 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on 2321901d8d22. We need to trigger more.
05/19/2015 04:00:55 INFO:	 We want to trigger 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on revision '2321901d8d22' a total of 20 time(s).
05/19/2015 04:00:58 INFO:	 There is a _build_ job that has completed successfully.
05/19/2015 04:00:58 INFO:	 We have the necessary files to trigger the downstream job.
05/19/2015 04:01:09 INFO:	 
05/19/2015 04:01:09 INFO:	 === e6565b1773b8 ===
05/19/2015 04:01:10 INFO:	 We want to have 20 job(s) of Windows 8 64-bit mozilla-inbound opt test mochitest-2 on revision e6565b1773b8
05/19/2015 04:01:11 INFO:	 We have found 0 potential job(s) matching 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on e6565b1773b8. We need to trigger more.
05/19/2015 04:01:11 INFO:	 We want to trigger 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on revision 'e6565b1773b8' a total of 20 time(s).
05/19/2015 04:01:13 INFO:	 We need to trigger the build job (1) in order to be able to run the test job (2)which we'll be triggered later
05/19/2015 04:01:13 INFO:	 We will trigger 1) 'WINNT 6.1 x86-64 mozilla-inbound build' instead of 2) 'Windows 8 64-bit mozilla-inbound opt test mochitest-2'
05/19/2015 04:01:14 INFO:	 
05/19/2015 04:01:14 INFO:	 === 0055add82982 ===
05/19/2015 04:01:15 INFO:	 We want to have 20 job(s) of Windows 8 64-bit mozilla-inbound opt test mochitest-2 on revision 0055add82982
05/19/2015 04:01:16 INFO:	 We have found 0 potential job(s) matching 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on 0055add82982. We need to trigger more.
05/19/2015 04:01:16 INFO:	 We want to trigger 'Windows 8 64-bit mozilla-inbound opt test mochitest-2' on revision '0055add82982' a total of 20 time(s).
05/19/2015 04:01:18 INFO:	 We need to trigger the build job (1) in order to be able to run the test job (2)which we'll be triggered later
05/19/2015 04:01:18 INFO:	 We will trigger 1) 'WINNT 6.1 x86-64 mozilla-inbound build' instead of 2) 'Windows 8 64-bit mozilla-inbound opt test mochitest-2'
05/19/2015 04:01:19 INFO:	 
05/19/2015 04:01:19 INFO:	 === d0129aa5b896 ===
05/19/2015 04:01:20 INFO:	 We want to have 20 job(s) of Windows 8 64-bit mozilla-inbound opt test mochitest-2 on revision d0129aa5b896
05/19/2015 04:01:25 ERROR:	 We have not found the job. If you see this problem please grep in builds-2015-05-11.js for 69421108 and run again with --debug and --dry-run. If you report this issue please upload the mentioned file somewhere for inspection. Thanks!
Traceback (most recent call last):
  File "trigger.py", line 189, in main
    files=options.files
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 395, in trigger_range
    successful_jobs, pending_jobs, running_jobs = _status_summary(matching_jobs)[0:3]
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 72, in _status_summary
    status = buildapi.query_job_status(job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildapi.py", line 153, in query_job_status
    req["request_id"])
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 170, in query_job_data
    "inspection. Thanks!" % (filename, request_id)
BuildjsonException: We have not found the job. If you see this problem please grep in builds-2015-05-11.js for 69421108 and run again with --debug and --dry-run. If you report this issue please upload the mentioned file somewhere for inspection. Thanks!
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/mozci/scripts$ grep 69421108 ~/.mozilla/mozci/builds-2015-05-11.js 
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/mozci/scripts$

**Comment by armenzg** [comment]
I'm afraid we won't be able to figure this out as much has landed since then.
