### ISSUE TITLE
Fix the readthedocs issue

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#22]
All the builds are currently failing or pending for days.
https://readthedocs.org/builds/mozilla-ci-tools/

**Comment by armenzg** [comment]
venv
-----

Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 2338, in <module>
    main()
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 984, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 1276, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/home/docs/checkouts/readthedocs.org/user_builds/mozilla-ci-tools/envs/master/bin/python'

**Comment by armenzg** [comment]
I fixed this issue.
The docs generation was being prompted to get_credentials(), however, we should not do that unless there is a user to input credentials.
https://groups.google.com/forum/#!topic/read-the-docs/ZthG3WzGHWc
