### ISSUE TITLE
Slowever connections leads to an incomplete JSON file leading to parse error

### ISSUE THREAD

**Issue by nigelbabu** [armenzg/mozilla_ci_tools#23]
```
(mozillaci)nigel:mozilla_ci_tools/ (master) $ python scripts/trigger.py --repo-name try --rev 4f2decfeb9c5 -b "Rev5 MacOSX Mountain Lion 10.8 try talos svgr" --debug                                                                                                 [19:55:22]
Traceback (most recent call last):
  File "scripts/trigger.py", line 8, in <module>
    from mozci.mozci import trigger_job, query_jobs_schedule_url
  File "/media/Seagate/mozilla/mozilla_ci_tools/mozci/mozci.py", line 14, in <module>
    from mozci.platforms import associated_build_job, does_builder_need_files
  File "/media/Seagate/mozilla/mozilla_ci_tools/mozci/platforms.py", line 12, in <module>
    data = sources.allthethings._fetch_json()
  File "/media/Seagate/mozilla/mozilla_ci_tools/mozci/sources/allthethings.py", line 34, in _fetch_json
    data = _fetch()
  File "/media/Seagate/mozilla/mozilla_ci_tools/mozci/sources/allthethings.py", line 24, in _fetch
    return req.json()
  File "/home/nigel/.virtualenvs/mozillaci/local/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/models.py", line 792, in json
    return json.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 157613 column 6 (char 5868703)
```

**Comment by armenzg** [comment]
Would you be able to try adding a timeout value? This way I can now what would work for your connection.
http://docs.python-requests.org/en/latest/user/advanced/#timeouts

**Comment by nigelbabu** [comment]
`req = requests.get(ALLTHETHINGS, timeout=(5, 300))`
This is what worked. We decided that 300 would default to a lower value configurable by an optional commandline option.

**Comment by vaibhavmagarwal** [comment]
This bug should be fixed as a side-effect of https://github.com/armenzg/mozilla_ci_tools/pull/66 
@nigelbabu : reopen this if you still face the error
