### ISSUE TITLE
Error when importing pushlog in mozci

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#25]
Traceback (most recent call last):
  File "parse_news.py", line 19, in <module>
    from utils import build_tbpl_link
  File "/home/vaibhav/alert_manager/utils.py", line 8, in <module>
    import mozci.sources.pushlog
  File "/home/vaibhav/alert_manager/venv/local/lib/python2.7/site-packages/mozci/sources/pushlog.py", line 23, in <module>
    import buildapi
  File "/home/vaibhav/alert_manager/venv/local/lib/python2.7/site-packages/mozci/sources/buildapi.py", line 21, in <module>
    from mozci.sources.pushlog import query_revision_info
ImportError: cannot import name query_revision_info

It looks like a cyclic dependency problem between buildapi and pushlog.

**Comment by armenzg** [comment]
Fixed in the 0.2.3 release:
https://github.com/armenzg/mozilla_ci_tools/commit/5953a9507f562f1e8c702b8e30b873839b2a5813
