### ISSUE TITLE
mozci-triggerbyfilters failed with "KeyError: 'requests'" exception

### ISSUE THREAD

**Issue by EricRahm** [armenzg/mozilla_ci_tools#296]
Attempting to retrigger some jobs on a try run I ran into an unhandled exception:

```
mozci-triggerbyfilters try d81a7a9390a6 -i mochitest-devtools-chrome --times 4
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
46 jobs will be triggered, do you wish to continue? y/n/d (d=show details) y
07/17/2015 02:42:10 INFO:	 We want to have 4 job(s) of Rev4 MacOSX Snow Leopard 10.6 try debug test mochitest-devtools-chrome-1 on revisions ['d81a7a9390a6']
07/17/2015 02:42:10 INFO:	 
07/17/2015 02:42:10 INFO:	 === d81a7a9390a6 ===
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
07/17/2015 02:42:10 INFO:	 We want to have 4 job(s) of Rev4 MacOSX Snow Leopard 10.6 try debug test mochitest-devtools-chrome-1 on revision d81a7a9390a6
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
07/17/2015 02:42:10 INFO:	 We have found 1 potential job(s) matching 'Rev4 MacOSX Snow Leopard 10.6 try debug test mochitest-devtools-chrome-1' on d81a7a9390a6. We need to trigger more.
Traceback (most recent call last):
  File "/usr/local/bin/mozci-triggerbyfilters", line 9, in <module>
    load_entry_point('mozci==0.10.0', 'console_scripts', 'mozci-triggerbyfilters')()
  File "/usr/local/lib/python2.7/dist-packages/mozci/scripts/triggerbyfilters.py", line 107, in main
    dry_run=options.dry_run,
  File "/usr/local/lib/python2.7/dist-packages/mozci/mozci.py", line 407, in trigger_range
    request_id = QUERY_SOURCE.get_buildapi_request_id(repo_name, matching_jobs[0])
  File "/usr/local/lib/python2.7/dist-packages/mozci/query_jobs.py", line 57, in get_buildapi_request_id
    return job["requests"][0]["request_id"]
KeyError: 'requests'
```

**Comment by vaibhavmagarwal** [comment]
This should be fixed in https://github.com/armenzg/mozilla_ci_tools/pull/297
@EricRahm : please comment/repoen this issue if you face it again. Thanks!
